version: '3.4'

services:
  proxy:
    image: nginx:1.13.8-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    environment:
      - NODE_ENV=test
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app